id: flow.freshchat.session.resolve.approve
triggers:
  - event_type: meya.freshworks.freshchat.event.session.resolve
    when: (@ user.approval == "pending" )

steps:
  - say: Your chat session with the live agent was ended but you still require an
      agent's approval.
  - delay: 1
  - ask: Would you like to try again?
    buttons:
      - text: Yes
        action:
          flow: flow.warranty
          jump: rma_approval
      - text: No
        action: end
---
id: flow.freshchat.session.resolve.support
triggers:
  - event_type: meya.freshworks.freshchat.event.session.resolve
    when: (@ user.support is sameas true )

steps:
  - user_set:
      support: None
  - say: Your chat session with the live agent ended.
  - delay: 1
  - flow: flow.initial
    transfer: true
