triggers:
  - agent_command: ^.*serial.*
    ignorecase: true
steps:
  - (serial_no)
  - ask: What is the device's serial number?
  - user_set: device_serial_no
  - say: Great, I just want to confirm the serial number.
  - say: >
      Are you sure this is the correct serial number?:
      (@ user.device_serial_no )
    quick_replies:
      - text: Yes
        action: next
      - text: No
        action:
          jump: serial_no
  - say: Ok great.

